copy /Y "D:\\SourceCodeTest\\Cryptography\\IcoFileSubjectInterfacePackage\\Debug\\$(TargetName).dll" "C:\\Windows\\SysWOW64\\$(TargetName).dll"
copy /Y "D:\\SourceCodeTest\\Cryptography\\IcoFileSubjectInterfacePackage\\Debug\\$(TargetName).exp" "C:\\Windows\\SysWOW64\\$(TargetName).exp"
copy /Y "D:\\SourceCodeTest\\Cryptography\\IcoFileSubjectInterfacePackage\\Debug\\$(TargetName).ilk" "C:\\Windows\\SysWOW64\\$(TargetName).ilk"
copy /Y "D:\\SourceCodeTest\\Cryptography\\IcoFileSubjectInterfacePackage\\Debug\\$(TargetName).lib" "C:\\Windows\\SysWOW64\\$(TargetName).lib"
copy /Y "D:\\SourceCodeTest\\Cryptography\\IcoFileSubjectInterfacePackage\\Debug\\$(TargetName).pdb" "C:\\Windows\\SysWOW64\\$(TargetName).pdb"
